USE project;
SELECT * FROM USER;
SELECT * FROM ORGANIZATION;
SELECT * FROM COMMENT;
SELECT * FROM POST;
SELECT * from USER JOIN ORGANIZATION USING(OrganizationID);
SELECT * FROM COMMENT WHERE PostID=1;